language: python
sudo: false
python:
- "2.7"
- "3.6"
install:
- pip install -e .
before_script:
- pip install --upgrade -r test_requirements.txt
script:
- py.test -v --cov ijroi ijroi
after_success:
- coveralls
